name: java-ci-actions
run-name: Execute some java-ci related actions 
on: [push]
jobs:
  java-project-ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: List current dir
          run: ls -la
          working-directory: rest-kotlin-maven
        # - name: Move to maven project dir
        #   run: cd ./rest-kotlin-maven
        # - name: List current dir
        #   run: ls -la
        - name: Run the Maven command
          run: mvn clean install
          working-directory: rest-kotlin-maven