name: java-ci-actions
run-name: Execute some java-ci related actions 
on: [push]
jobs:
  java-project-ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: List maven dir
          run: ls -la
          working-directory: rest-kotlin-maven
        - name: Build with Maven
          run: mvn clean install
          working-directory: rest-kotlin-maven
        - name: List current dir
          run: ls -la
        - name: List gradle dir
          run: ls -la
          working-directory: rest-kotlin-gradle
        - name: Build with Gradle
          run: ./gradlew clean build
          working-directory: rest-kotlin-gradle